- name: Hello World Sample
  hosts: all
  gather_facts: yes
  become: true
  tasks :
   - name: Connection Check
     ping:
   - name: Update apt packages
     apt:
       update_cache: yes
   - name: Upgrade all packages to the latest version   
     apt:
       name: "*"
       state: latest
