- name: Hello World Sample
  hosts: all
  gather_facts: yes
  become: true
  tasks :
   - name: packages | ensure apt list dir exists
     file:
       path: /var/lib/apt/lists/
       state: directory
       mode: 0755
   - name: Connection Check
     ping:
   - name: Update apt packages
     apt:
      update_cache: yes
